### ISSUE TITLE
Unable to enable extension for backend

### ISSUE THREAD

**Issue by michaelborn** [positron48/prism-code-highlight#1]
It looks as though the extension does not work in Bolt 5 on the backend. Setting `backend: true` throws this error:

![Screenshot from 2022-06-03 12-55-17](https://user-images.githubusercontent.com/8106227/171910898-fa6ac33d-697c-4eb5-9619-84c0c97d4786.png)

**Comment by positron48** [comment]
I didn't think that somebody will try to enable extension on the backend. Bolt's admin pages does not include `<pre>` tag as I see.

Anyway i will try to fix it tomorrow. Can you show where you want to see prism on backend?

**Comment by michaelborn** [comment]
I only enabled it to see what the config editors looked like. Don't feel like you need to "fix" or implement this... but I would recommend removing that option from the extension config file so other folks don't try to enable backend code highlighting.

I can submit a PR to hide that config for now.

**Comment by positron48** [comment]
Thanks for feedback. Remove option from config is too simple)

I fixed it by removing second param from asset(). I think prism may be useful in some custom admin pages added from extensions. Now it must work (it work on my test page).

**Comment by positron48** [comment]
Now bolt 4 is broken. I'm looking for a better solution

**Comment by positron48** [comment]
Now it's probably good. Sorry for this spam)

**Comment by michaelborn** [comment]
You rock, @positron48 ! Thank you!
